(function (global) {
  "use strict";

  const namespace = (global.AIChatExporter = global.AIChatExporter || {});
  const common = namespace.AdapterCommon;

  namespace.GrokAdapter = {
    extract() {
      return common.extractWithConfig({
        platformLabel: "Grok",
        rootSelector: "main",
        titleSelectors: [
          "[data-testid='conversation-title']",
          "[aria-current='page']",
          "h1"
        ],
        messageSelectors: [
          {
            role: "user",
            selectors: [
              "[data-testid='user-message']",
              "[data-testid='message-bubble-user']",
              "[data-testid='human-message']",
              "[data-testid*='user' i][data-testid*='message' i]",
              "[data-testid*='message' i][data-testid*='user' i]",
              "[data-author='user']",
              "[data-role='user']",
              "[class*='user-message']",
              "[class*='human-message']",
              ".user-message"
            ],
            contentSelectors: [
              ".prose",
              ".markdown",
              "[class*='prose']",
              "[class*='markdown']",
              "[data-testid*='markdown' i]",
              "[data-testid*='response-content' i]",
              "[data-testid='message-content']",
              ".message-content"
            ]
          },
          {
            role: "assistant",
            selectors: [
              ".response-content-markdown",
              "[class*='response-content-markdown']",
              ".response-content-markdown h1",
              ".response-content-markdown h2",
              ".response-content-markdown h3",
              ".response-content-markdown h4",
              ".response-content-markdown h5",
              ".response-content-markdown h6",
              ".response-content-markdown p",
              "[data-testid='assistant-message']",
              "[data-testid='message-bubble-assistant']",
              "[data-testid='model-message']",
              "[data-testid='grok-message']",
              "[data-testid*='assistant' i][data-testid*='message' i]",
              "[data-testid*='grok' i][data-testid*='message' i]",
              "[data-testid*='model' i][data-testid*='message' i]",
              "[data-testid*='response' i]",
              "[data-testid*='answer' i]",
              "[data-author='assistant']",
              "[data-role='assistant']",
              "ul",
              "ol",
              "li",
              "pre",
              "pre code",
              "[data-testid*='code' i]",
              "[data-test-id*='code' i]",
              "[class*='code-block']",
              "[class*='codeBlock']",
              "[class*='assistant-message']",
              "[class*='model-message']",
              "[class*='grok-message']",
              "[class*='markdown']",
              "[class*='prose']",
              ".assistant-message",
              ".model-response"
            ],
            expandClosestSelectors: [
              ".response-content-markdown",
              "[class*='response-content-markdown']",
              "[data-testid='assistant-message']",
              "[data-testid='message-bubble-assistant']",
              "[data-testid='model-message']",
              "[data-testid='grok-message']",
              "[data-testid*='assistant' i][data-testid*='message' i]",
              "[data-testid*='grok' i][data-testid*='message' i]",
              "[data-testid*='model' i][data-testid*='message' i]",
              "[data-testid*='response' i]",
              "[data-testid*='answer' i]",
              "[class*='assistant-message']",
              "[class*='model-message']",
              "[class*='grok-message']",
              ".assistant-message",
              ".model-response",
              ".message-content",
              ".markdown",
              ".prose",
              "[class*='markdown']",
              "[class*='prose']",
              "article"
            ],
            excludeClosestSelectors: [
              "[data-testid='user-message']",
              "[data-testid='message-bubble-user']",
              "[data-testid='human-message']",
              "[data-testid*='user' i][data-testid*='message' i]",
              "[data-author='user']",
              "[data-role='user']",
              "[class*='user-message']",
              "[class*='human-message']",
              "button",
              "nav",
              "header",
              "footer",
              "form",
              "textarea",
              "input",
              "select",
              "[role='button']",
              "[role='navigation']",
              "[role='menu']"
            ],
            contentSelectors: [
              ".prose",
              ".markdown",
              "[class*='prose']",
              "[class*='markdown']",
              "[data-testid*='markdown' i]",
              "[data-testid*='response-content' i]",
              "[data-testid='message-content']",
              ".message-content"
            ]
          }
        ],
        fallbackMessageSelectors: [
          ".response-content-markdown",
          "[class*='response-content-markdown']",
          "[data-testid*='message' i]",
          "[data-testid*='response' i]",
          "[data-testid*='answer' i]",
          "ul",
          "ol",
          "li",
          "pre",
          "pre code",
          "[data-testid*='code' i]",
          "[data-test-id*='code' i]",
          "[class*='code-block']",
          "[class*='codeBlock']",
          "[class*='message-bubble']",
          "[class*='messageBubble']",
          "[class*='chat-message']",
          "[class*='assistant-message']",
          "[class*='user-message']",
          "[class*='markdown']",
          "[class*='prose']",
          "article"
        ],
        fallbackExpandClosestSelectors: [
          ".response-content-markdown",
          "[class*='response-content-markdown']",
          "[data-testid='assistant-message']",
          "[data-testid='message-bubble-assistant']",
          "[data-testid='model-message']",
          "[data-testid='grok-message']",
          "[data-testid*='assistant' i][data-testid*='message' i]",
          "[data-testid*='grok' i][data-testid*='message' i]",
          "[data-testid*='model' i][data-testid*='message' i]",
          "[data-testid*='response' i]",
          "[data-testid*='answer' i]",
          "[class*='assistant-message']",
          "[class*='model-message']",
          "[class*='grok-message']",
          ".assistant-message",
          ".model-response",
          ".message-content",
          ".markdown",
          ".prose",
          "[class*='markdown']",
          "[class*='prose']",
          "article"
        ],
        fallbackExcludeClosestSelectors: [
          "[data-testid='user-message']",
          "[data-testid='message-bubble-user']",
          "[data-testid='human-message']",
          "[data-testid*='user' i][data-testid*='message' i]",
          "[data-author='user']",
          "[data-role='user']",
          "[class*='user-message']",
          "[class*='human-message']",
          "button",
          "nav",
          "header",
          "footer",
          "form",
          "textarea",
          "input",
          "select",
          "[role='button']",
          "[role='navigation']",
          "[role='menu']"
        ],
        alternatingFallbackRoles: true,
        mergeAdjacentSameRole: true,
        dropAssistantEchoesOfUser: true
      });
    }
  };
})(globalThis);
